[databases]
main ansible_host=158.160.49.210 fqdn=fhm95vbpva3terkurhrm.auto.internal
replica ansible_host=62.84.114.238 fqdn=fhmcmd8g43nfjqne8a0g.auto.internal

[storage]
storage ansible_host=89.169.128.60 fqdn=fhm07mvrj0hhdoslik0l.auto.internal

[webservers]
web-1 ansible_host=111.88.253.194 fqdn=fhmv8ng63a5v4a6ekd4q.auto.internal
web-2 ansible_host=51.250.76.66 fqdn=fhmnv6qdole3riukpn56.auto.internal

[all:vars]
ansible_user=ubuntu
